CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10,2),
    DATA_LIMIT NUMBER,
    MINUTE_LIMIT NUMBER,
    SMS_LIMIT NUMBER
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100),
    SIGNUP_DATE DATE,
    TARIFF_ID NUMBER,
    CONSTRAINT FK_CUSTOMERS_TARIFF
        FOREIGN KEY (TARIFF_ID)
        REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    STAT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    DATA_USAGE NUMBER,
    DATA_USAGE_PERCENT NUMBER,
    MINUTE_USAGE NUMBER,
    SMS_USAGE NUMBER,
    PAYMENT_STATUS VARCHAR2(30),
    CONSTRAINT FK_STATS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX IDX_CUSTOMERS_CITY ON CUSTOMERS(CITY);
CREATE INDEX IDX_CUSTOMERS_TARIFF ON CUSTOMERS(TARIFF_ID);
CREATE INDEX IDX_STATS_CUSTOMER ON MONTHLY_STATS(CUSTOMER_ID);